import MainSection from "@/components/Boxes/MainSection";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { GaleriesProvider, LangProvider, TableauxProvider } from "@/context/Context";
import type { Metadata } from "next";
import { Merriweather, Playfair_Display, Poppins } from 'next/font/google';
import "./embla.css";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
})

const merriweather = Merriweather({
  weight: "400",
  subsets:['latin'],
  display:"swap",
  variable:"--meriweather"
})

const poppins = Poppins({
  weight: "600",
  subsets:['latin'],
  display:"swap",
  variable:"--poppins"
})
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${playfair.className} ${merriweather.variable} ${poppins.variable} antialiased bg-primary flex flex-col gap-5 max-w-screen min-h-svh`}
      >
        <LangProvider>
          <GaleriesProvider>
            <TableauxProvider>
              <Header></Header>
              <MainSection>
                {children}
              </MainSection>
              <Footer></Footer>
            </TableauxProvider>
          </GaleriesProvider>
        </LangProvider>
      </body>
    </html> 
  );
}
